# Change these first
owner: P1N2O # Your GitHub username
repo: dev-pinto-status # Your GitHub repository name

# Add your sites here
sites:
  - name: PINTO.DEV
    url: https://pinto.dev
  - name: LAB.PINTO.DEV
    url: https://lab.pinto.dev
#   - name: API.PINTO.DEV
#     url: https://api.pinto.dev
#   - name: POST to Google
#     url: https://www.google.com
#     method: POST

status-website:
#   Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.pinto.dev
#   Uncomment the following line if you don't have a custom domain and add your repo name
#   baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PINTO.DEV — Status
#   introTitle: "Track Real-time status of **[PINTO.DEV](https://pinto.dev)** end-points"
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: https://pinto.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
